return {
  {
    "nvim-treesitter/nvim-treesitter-context",
    enabled = true,
    opts = {
        mode = "cursor",
        max_lines = 3,
        highlight = { enable = true },
        indent = { enable = true },
        ensure_installed = {
            "bash",
            "c",
            "diff",
            "html",
            "javascript",
            "jsdoc",
            "json",
            "jsonc",
            "lua",
            "luadoc",
            "luap",
            "markdown",
            "markdown_inline",
            "python",
            "query",
            "regex",
            "toml",
            "tsx",
            "vim",
            "vimdoc",
            "yaml",
          },
    },
  },
}
