-- Generates the keymap cheatsheet (docs/KEYMAPS.md and doc/ftvim-keymaps.txt) from the keymaps
-- FtVim actually defines, so the docs never drift from the code.
--   nvim --headless -u tests/minimal_init.lua "+luafile scripts/gen-docs.lua"

local root = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p:h:h")

local function generate()
  vim.api.nvim_exec_autocmds("User", { pattern = "VeryLazy" })
  vim.wait(2000, function()
    return package.loaded["which-key"] and require("which-key.config").loaded
  end)

  local leader = vim.g.mapleader
  local function pretty(lhs)
    lhs = vim.fn.keytrans(vim.keycode(lhs)):gsub("<NL>", "<C-J>")
    if vim.startswith(lhs, "<Space>") and leader == " " then
      lhs = "<leader>" .. lhs:sub(8)
    end
    return lhs
  end

  -- Keymaps set by FtVim and its plugins (recorded by tests/minimal_init.lua) that still exist
  local recorded = {}
  for _, map in ipairs(_G.FTVIM_KEYMAP_LOG or {}) do
    recorded[map.mode .. pretty(map.lhs)] = true
  end
  local rows, seen = {}, {}
  for _, mode in ipairs { "n", "x", "i", "t" } do
    for _, map in ipairs(vim.api.nvim_get_keymap(mode)) do
      local lhs = pretty(map.lhs)
      local key = lhs .. "\0" .. (map.desc or "")
      local was_recorded = recorded[mode .. lhs] or (mode == "x" and recorded["v" .. lhs])
      if map.desc and was_recorded and not lhs:match "^<Plug>" and not seen[key .. mode] then
        seen[key .. mode] = true
        rows[#rows + 1] = { lhs = lhs, desc = map.desc, mode = mode }
      end
    end
  end
  for _, key in ipairs(require("ftvim.lsp.keymaps").keys) do
    local modes = type(key.mode) == "table" and key.mode or { key.mode or "n" }
    for _, mode in ipairs(modes) do
      rows[#rows + 1] = { lhs = key[1], desc = "LSP: " .. key.desc, mode = mode, lsp = true }
    end
  end

  -- Merge modes of identical mappings
  local merged, order = {}, {}
  for _, row in ipairs(rows) do
    local id = row.lhs .. "\0" .. row.desc
    if merged[id] then
      if not vim.tbl_contains(merged[id].modes, row.mode) then
        table.insert(merged[id].modes, row.mode)
      end
    else
      merged[id] = { lhs = row.lhs, desc = row.desc, modes = { row.mode }, lsp = row.lsp }
      order[#order + 1] = id
    end
  end

  -- Groups: which-key group names for <leader> prefixes
  local groups = {}
  for _, m in ipairs(require("which-key.config").mappings) do
    if m.group and m.desc then
      groups[pretty(m.lhs)] = m.desc
    end
  end
  local function section(item)
    if item.lsp then
      return "LSP (when a language server is attached)"
    end
    local prefix = item.lhs:match "^(<leader>.)"
    if prefix and groups[prefix] then
      return groups[prefix] .. " (" .. prefix .. ")"
    end
    return prefix and "Leader" or "General"
  end

  local sections, section_order = {}, {}
  for _, id in ipairs(order) do
    local item = merged[id]
    local name = section(item)
    if not sections[name] then
      sections[name] = {}
      section_order[#section_order + 1] = name
    end
    table.insert(sections[name], item)
  end
  table.sort(section_order, function(a, b)
    local rank = function(s)
      return s == "General" and 0 or s:match "^LSP" and 2 or 1
    end
    if rank(a) ~= rank(b) then
      return rank(a) < rank(b)
    end
    return a < b
  end)
  for _, name in ipairs(section_order) do
    table.sort(sections[name], function(a, b)
      return a.lhs:lower() < b.lhs:lower() or (a.lhs:lower() == b.lhs:lower() and a.lhs < b.lhs)
    end)
  end

  -- docs/KEYMAPS.md
  local md = {
    "# FtVim keymaps",
    "",
    "<!-- Generated by scripts/gen-docs.lua. Do not edit by hand. -->",
    "",
    "`<leader>` is `Space`. Includes the keymaps of the `lang.42` and `dap` extras.",
    "Inside Neovim, `<leader>Fk` searches all keymaps and `:help ftvim-keymaps` shows this list.",
  }
  local help = {
    "*ftvim-keymaps.txt*  FtVim keymaps",
    "",
    "Generated by scripts/gen-docs.lua. <leader> is Space.",
    "",
  }
  for _, name in ipairs(section_order) do
    vim.list_extend(md, { "", "## " .. name, "", "| Keys | Mode | Description |", "| --- | --- | --- |" })
    vim.list_extend(
      help,
      { "==============================================================================", name, "" }
    )
    for _, item in ipairs(sections[name]) do
      local keys = item.lhs:gsub("|", "\\|")
      md[#md + 1] = ("| `%s` | %s | %s |"):format(keys, table.concat(item.modes, ", "), item.desc)
      help[#help + 1] = ("  %-22s %-6s %s"):format(item.lhs, table.concat(item.modes, ","), item.desc)
    end
    help[#help + 1] = ""
  end
  help[#help + 1] = " vim:tw=78:ts=8:ft=help:norl:"

  vim.fn.mkdir(root .. "/docs", "p")
  vim.fn.mkdir(root .. "/doc", "p")
  vim.fn.writefile(md, root .. "/docs/KEYMAPS.md")
  vim.fn.writefile(help, root .. "/doc/ftvim-keymaps.txt")
  io.stdout:write(("Wrote %d keymaps\n"):format(#order))
end

vim.api.nvim_create_autocmd("VimEnter", {
  once = true,
  callback = vim.schedule_wrap(function()
    local ok, err = pcall(generate)
    if not ok then
      io.stderr:write(tostring(err) .. "\n")
    end
    os.exit(ok and 0 or 1)
  end),
})
